"""
pdf_extractor.py — Extract text from IIT Jammu PDFs and convert to Markdown

Reads PDF URLs from data/raw/_pdfs.txt (generated by crawler)
Converts each PDF → clean markdown → saves in data/raw/

Usage:
    python pdf_extractor.py
"""

import os
import re
import logging
import requests
from pathlib import Path
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

# ── CONFIG ─────────────────────────────────────────────
RAW_DATA_DIR = Path(os.getenv("RAW_DATA_DIR", "../data/raw"))
PDF_LIST_FILE = RAW_DATA_DIR / "_pdfs.txt"

logger = logging.getLogger(__name__)

# ── PDF → MARKDOWN FUNCTION ─────────────────────────────
def extract_pdf_to_markdown(source: str, output_name: Optional[str] = None) -> Optional[str]:
    try:
        import fitz  # PyMuPDF
    except ImportError:
        logger.error("❌ PyMuPDF not installed. Run: pip install PyMuPDF")
        return None

    pdf_bytes = None

    # ── Load PDF (URL or local) ───────────────────────
    try:
        if source.startswith("http"):
            resp = requests.get(source, timeout=30, headers={
                "User-Agent": "IITJammuBot/1.0"
            })
            resp.raise_for_status()
            pdf_bytes = resp.content
        else:
            path = Path(source)
            if not path.exists():
                logger.warning(f"PDF not found: {source}")
                return None
            pdf_bytes = path.read_bytes()
    except Exception as e:
        logger.warning(f"❌ Failed to load PDF: {e}")
        return None

    # ── Open PDF ──────────────────────────────────────
    try:
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    except Exception as e:
        logger.warning(f"❌ Failed to open PDF: {e}")
        return None

    lines = [
        f"# {doc.metadata.get('title', 'IIT Jammu Document')}",
        f"\n**Source:** {source}",
        f"\n**Pages:** {doc.page_count}",
        "\n---\n"
    ]

    # ── Extract text ───────────────────────────────────
    for page_num in range(doc.page_count):
        page = doc.load_page(page_num)
        blocks = page.get_text("blocks")

        lines.append(f"\n## Page {page_num + 1}\n")

        for block in blocks:
            text = block[4].strip()

            if not text or len(text) < 2:
                continue

            # Headings detection
            if len(text) < 80 and text.isupper():
                lines.append(f"\n### {text.title()}\n")
            elif len(text) < 100 and block[1] < 150:
                lines.append(f"\n**{text}**\n")
            else:
                lines.append(text)

    doc.close()

    # ── Clean text ─────────────────────────────────────
    content = "\n".join(lines)
    content = re.sub(r"\n{4,}", "\n\n\n", content)
    content = re.sub(r"[ \t]{3,}", " ", content)

    # ── Save to file ───────────────────────────────────
    if output_name:
        RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
        out_path = RAW_DATA_DIR / output_name
        out_path.write_text(content, encoding="utf-8")
        logger.info(f"✅ Saved: {out_path}")

    return content


# ── PROCESS ALL PDFs FROM LIST ─────────────────────────
def extract_from_pdf_list():
    if not PDF_LIST_FILE.exists():
        logger.warning("❌ _pdfs.txt not found in data/raw/")
        return

    urls = PDF_LIST_FILE.read_text().splitlines()

    logger.info(f"📄 Found {len(urls)} PDFs to process")

    success = 0
    skipped = 0

    for url in urls:
        try:
            filename = url.split("/")[-1].split("?")[0]

            # Skip junk PDFs
            if any(x in url.lower() for x in ["tender", "form", "circular"]):
                skipped += 1
                continue

            md_name = filename.replace(".pdf", ".md")
            out_path = RAW_DATA_DIR / md_name

            # Skip already processed
            if out_path.exists():
                skipped += 1
                continue

            logger.info(f"📥 Extracting: {filename}")

            result = extract_pdf_to_markdown(url, md_name)

            # Skip low-quality PDFs
            if result and len(result) > 500:
                success += 1
            else:
                logger.warning(f"⚠️ Low content: {filename}")
                skipped += 1

        except Exception as e:
            logger.warning(f"❌ Error processing {url}: {e}")
            skipped += 1

    logger.info(f"""
📊 PDF Extraction Summary
    Success : {success}
    Skipped : {skipped}
""")


# ── MAIN ───────────────────────────────────────────────
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

    extract_from_pdf_list()